spring:
  application:
    name: image-api
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: admin2022
      database: image
      port: 27017
      host: localhost
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 6000

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: 8220
  servlet:
    context-path: /image
  errorResponse:
    include-message: always
    inlucde-binding-errors: always

logging:
  level:
    com.pragma: DEBUG
